CREATE DATABASE HEALTH_INSURANCE

USE HEALTH_INSURANCE


SELECT * FROM INSURANCE;

--DATA CLEANING

-- FIND NULL VALUES ROW

SELECT
* FROM INSURANCE
WHERE  age IS NULL OR
	   sex IS NULL OR
	   bmi IS NULL OR
	   children IS NULL OR
	   smoker IS NULL OR
	   region IS NULL OR
	   charges IS NULL

-- TRIM ALL THE COLUMN WHERE EXTRA SPACES
UPDATE INSURANCE
SET region = LTRIM(RTRIM(region));

UPDATE INSURANCE
SET region = TRIM(region);


-- SMOKER VALUES IN UPPER CASE 

UPDATE INSURANCE
SET smoker = UPPER(smoker);


-- HERE I'M FINDING TOTAL NUMBER OF SAME AGES.

SELECT 
	age,
	COUNT(age) AS total_of_same
FROM INSURANCE
GROUP BY age
ORDER BY age;


-- HERE I'M FINDING HOW MANY CUSTOMER IS MALE AND FEMALE

SELECT
COUNT(CASE WHEN sex = 'male' THEN 1 END) AS TOTAL_MALE,
COUNT(CASE WHEN sex = 'female' THEN 1 END) AS TOTAL_FEMALE
FROM INSURANCE


-- WHAT IS THE PERCENTAGE OF MALE AND FEMALE

SELECT
ROUND(COUNT(CASE WHEN sex = 'male' THEN 1 END)*100.0/COUNT(sex),2) AS TOTAL_MALE,
ROUND(COUNT(CASE WHEN sex = 'female' THEN 1 END)*100.0/COUNT(sex),2) AS TOTAL_FEMALE
FROM INSURANCE


-- HOW MANY MALE AND FEMALE AGE IS BETWEEN 18 TO 30

SELECT
COUNT(CASE WHEN sex = 'male' THEN 1 END) AS TOTAL_MALE,
COUNT(CASE WHEN sex = 'female' THEN 1 END) AS TOTAL_FEMALE
FROM INSURANCE
WHERE age BETWEEN 18 AND 30;


-- HOW MANY MALE AND FEMALE AGE IS BETWEEN 30 TO 40

SELECT
COUNT(CASE WHEN sex = 'male' THEN 1 END) AS TOTAL_MALE,
COUNT(CASE WHEN sex = 'female' THEN 1 END) AS TOTAL_FEMALE
FROM INSURANCE
WHERE age BETWEEN 30 AND 40;


-- HOW MANY MALE AND FEMALE AGE IS BETWEEN 40 TO 60

SELECT
	COUNT(CASE WHEN sex = 'male' THEN 1 END) AS TOTAL_MALE,
	COUNT(CASE WHEN sex = 'female' THEN 1 END) AS TOTAL_FEMALE
FROM INSURANCE
WHERE age BETWEEN 40 AND 60;


-- HOW MANY MALE AND FEMALE AGE IS >60

SELECT
	COUNT(CASE WHEN sex = 'male' THEN 1 END) AS TOTAL_MALE,
	COUNT(CASE WHEN sex = 'female' THEN 1 END) AS TOTAL_FEMALE
FROM INSURANCE
WHERE age>60


-- HOW MANY CUSTOMER IS SMOKING

SELECT 
	COUNT(CASE WHEN smoker ='YES' THEN 1 END) AS SMOKING,
	COUNT(CASE WHEN smoker ='NO' THEN 1 END) AS NOT_SMOKING
FROM INSURANCE


-- HOW MANY MALE AND FEMALE CUSTOMER IS SMOKING

SELECT 
	sex AS GENDER,
	COUNT(CASE WHEN smoker ='YES' THEN 1 END) AS SMOKING
FROM INSURANCE
GROUP BY sex;


-- HOW MANY MALE AND FEMALE IS NOT SMOKING

SELECT
	sex AS GENDER,
	COUNT(CASE WHEN smoker = 'NO' THEN 1 END) AS NOT_SMOKING
FROM INSURANCE
GROUP BY sex;

-- TOTAL OF AGE PERSON IS SMOKING

SELECT 
	age AS AGE,
	COUNT(CASE WHEN smoker = 'YES' THEN 1 END) AS TOTAL_SMOKING
FROM INSURANCE
GROUP BY age
ORDER BY COUNT(CASE WHEN smoker = 'YES' THEN 1 END) DESC;



-- TOTAL NUMBER OF DIFFERENT REGION 

SELECT
	region,
	COUNT(region) AS TOTAL_REGION
FROM INSURANCE
GROUP BY region
ORDER BY COUNT(region) DESC;



-- Total Number of customers with children

SELECT
	COUNT(children) AS T_C_CHILD
FROM INSURANCE
WHERE children>0;


-- WHAT IS THE AVERAGE NUMBER OF CHILDREN 

SELECT
	AVG(children) AS AVG_CHILDREN
FROM INSURANCE;


-- WHAT IS THE MAX,MIN,AVG CHARGES

SELECT
 AVG(charges) AS AVG_CHARGES,
 MIN(charges) AS MIN_CHARGES,
 MAX(charges) AS MAX_CHARGES
FROM INSURANCE


-- WHAT IS THE AVG BMI OF FEMALES

SELECT
	ROUND(AVG(bmi),2) AS F_AVG_BMI
FROM INSURANCE
WHERE sex = 'female';



-- WHAT IS THE AVG BMI OF MALES

SELECT
	ROUND(AVG(bmi),2) AS M_AVG_BMI
FROM INSURANCE
WHERE sex = 'male';


-- WHAT IS THE AVERAGE CHARGES OF DIFFERENT REGION 

SELECT
	AVG(CASE WHEN region = 'southwest' THEN charges END) AS SW_AVG,
	AVG(CASE WHEN region = 'northwest' THEN charges END) AS NW_AVG,
	AVG(CASE WHEN region = 'southeast' THEN charges END) AS SE_AVG,
	AVG(CASE WHEN region = 'northeast' THEN charges END) AS NE_AVG
FROM INSURANCE;


-- WHAT IS THE SUM CHARGES OF DIFFERENT REGION 

SELECT
	SUM(CASE WHEN region = 'southwest' THEN charges END) AS SW_SUM,
	SUM(CASE WHEN region = 'northwest' THEN charges END) AS NW_SUM,
	SUM(CASE WHEN region = 'southeast' THEN charges END) AS SE_SUM,
	SUM(CASE WHEN region = 'northeast' THEN charges END) AS NE_SUM
FROM INSURANCE;


-- WHAT IS THE AVG CHARGES ACCORDING TO DIFFERENT GENDER

SELECT
	ROUND(AVG(CASE WHEN sex = 'male' THEN charges END),2) AS M_AVG_CHARGES,
	ROUND(AVG(CASE WHEN sex = 'female' THEN charges END),2) AS F_AVG_CHARGES
FROM INSURANCE


-- TOTAL NUMBER OF FEMALE FOR DIFFERENT AGE

SELECT
	age,
	COUNT(sex) Total_female
FROM INSURANCE
GROUP BY age,sex
HAVING sex = 'female'
ORDER BY COUNT(sex) DESC;



-- TOTAL NUMBER OF MALE FOR DIFFERENT AGE

SELECT
	age,
	COUNT(sex) Total_male
FROM INSURANCE
WHERE sex = 'male'
GROUP BY sex,age
ORDER BY COUNT(sex) DESC;


-- CALUCATE PERCENTAGE OF CHARGES BY REGION

SELECT
	region,
	ROUND(SUM(charges),2) Sum_charges,
	(ROUND(SUM(charges)*100.0/ SUM(SUM(charges)) OVER(),2)) Percentage
FROM INSURANCE
GROUP BY region
ORDER BY SUM(charges)*100.0/ SUM(SUM(charges)) OVER() DESC;